version: "3.9"

x-uffizzi-ingress:
  service: app
  port: 80

services:
  app:
    depends_on:
      - "postgres"
    image: nginx
    ports:
      - 3001:3001
    environment:
      ALL_YES: 1
      NO_INQUIRY: 0
      TRUST_PROXY_HEADER: 1
      DB_URL: postgres://postgres:p0stgr3s@localhost:5432
    deploy:
      resources:
        limits:
          memory: 2000M

  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr3s"
    deploy:
      resources:
        limits:
          memory: 500M

x-uffizzi-continuous-preview:
  share_to_github: false
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: false
  deploy_preview_when_image_tag_is_created: false
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
